version: "3"
services:
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    container_name: db
  app:
    build: ./
    volumes:
      - app:/app
    ports:
      - "5001:5001"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    container_name: app
volumes:
  db:
  app:
networks:
  default:
    name: my_network
    external: true
